
# Current path
RFNOC_FPGA_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Include Makefile.srcs for all subdirectories automatically
SUBDIRS_MAKEFILE_SRCS = $(wildcard $(RFNOC_FPGA_DIR)/*/Makefile.srcs)
include $(SUBDIRS_MAKEFILE_SRCS)

LIB_IP_XCI_SRCS += $(LIB_IP_PULSE_SHAPING_FILTER_SRCS)
LIB_IP_XCI_SRCS += $(LIB_IP_ADD_PRE_PHASE_SRCS)
LIB_IP_XCI_SRCS += $(LIB_IP_C_ADDSUB_0_SRCS)
LIB_IP_XCI_SRCS += $(LIB_IP_CMPY_0_SRCS)
LIB_IP_XCI_SRCS += $(LIB_IP_NCO_SRCS)
